-- creating table
Create table Employee_Attrition_tb
(
Emp_id varchar(20) primary key,
Age int not null,
Age_group int not null,
Attrition Boolean not null,
Business_Travel varchar(20) not null,
Daily_Rate int not null,
Department varchar(50)not null,
DistanceFromHome varchar(10) not null,
Education int not null,
Education_Field varchar(30),
Employee_count int not null, 
Employee_number int not null, 
Enviourment_Satisfaction int not null,
Gender varchar(10) not null,
Hourly_rate int not null,
job_involvment int not null,
job_level int not null,
job_role varchar(20),
job_satisfaction int not null,
Marital_status varchar(20)not null,
Monthly_income int not null,
salary_slab varchar(20) not null,
Monthly_rate int not null,
NumOfworkedInCompany int not null,
over18 varchar(10)not null,
OverTime varchar(10)not null,
present_salary_hike int not null,
performance_rating int not null,
Relationship_satisfaction int not null,
standard_hours int not null,
stock_option_level int not null,
Total_Working_Years int not null,
Training_Time_LastYear int not null,
work_life_balance int not null,
YearsAtCompany int not null,
YearsINCurrentRole int not null,
YearsSinceLastPromption int not null,
YearsWithCurrentManager int not null
);

select * from Employee_Attrition_tb;